### ISSUE TITLE
Roadmap for foo_dsp_effect 0.20

### ISSUE THREAD

**Issue by mudlord** [mudlord/foobar2000#1]
- [x] Rewrite components for DUI elements integration
  - \- [x] Pitch/tempo/samplerate shift
  - \- [x] IIR filters
  - \- [x] WahWah
  - \- [x] Echo
  - \- [x] Reverb
  - \- [x] Phaser
- [x] Fix buffering for pitch/tempo/samplerate shift
- [x] Implement Rubberband library for pitch/tempo/samplerate shift
- [x] Rewrite menu access for DSPs
- [x] Farm off the deemphasis filter to a seperate component

**Comment by kddlb** [comment]
Clicking on the "rails" of the sliders for pitch/tempo/rate shifting in the DUI component doesn't affect the DSP.

**Comment by mudlord** [comment]
This was done to facilitate smooth changes. I wanted to track when a mouse button is released after its dragged. So then it doesn't abruptly change the rates and cause massive distortion like before. 

I need to work out if WTL allows for just clicking on a different area of the bar, disregarding any possible movement while still allowing the new behaviour..

**Comment by mudlord** [comment]
3805f81a668be16e0fbe7a823dbd769e24893108 should fix it now. I'll do a compile ASAP.

**Comment by kddlb** [comment]
Got a crash while fuzzying it. 
[crash reports.zip](https://github.com/mudlord/foobar2000/files/852840/crash.reports.zip)

**Comment by mudlord** [comment]
Reading the minidump I now got a pretty good clue why it crashes for you. 👍

**Comment by mudlord** [comment]
https://github.com/mudlord/foobar2000/commit/2661acbae709123ca0fd261128c3d36c759dd611 seems to fix it on my end.

**Comment by kddlb** [comment]
Another crash 😢  when changing tracks while Rubber Band time stretching is engaged.

[crash report 2.zip](https://github.com/mudlord/foobar2000/files/852983/crash.report.2.zip)

**Comment by mudlord** [comment]
Can you try again and upload the crash report if any?

**Comment by kddlb** [comment]
[crash report 3.zip](https://github.com/mudlord/foobar2000/files/853000/crash.report.3.zip)

**Comment by mudlord** [comment]
Should all be fixed now.
